@startuml diagramaSequenciaUC01_TaskPrazo

title Diagrama de Sequência referente ao UC-01: Criar Tarefa (Tipo Prazo)

actor User
participant Frontend
participant TaskController
participant TaskService
participant TaskRepository
participant Task
participant Database

User -> Frontend: Criar tarefa do tipo Prazo
activate Frontend
Frontend -> TaskController: POST /task/create/prazo
activate TaskController
TaskController -> TaskService: createPrazoTask(DTOCreatePrazoTask)
activate TaskService
alt if descrição inválida
    TaskService --> TaskController: throw IllegalArgumentException
    TaskController --> User: HTTP 400 BAD REQUEST
else if dias planejados inválidos
    TaskService --> TaskController: throw IllegalArgumentException
    TaskController --> User: HTTP 400 BAD REQUEST
else else
    TaskService -> Task: Task(description, TaskTypeEnum.PRAZO, priority, plannedDays)
    TaskService -> TaskRepository: save(Task)
    activate TaskRepository
    TaskRepository -> Database: INSERT INTO tasks VALUES (...)
    activate Database
    Database --> TaskRepository: Saved Task
    deactivate Database
    TaskRepository --> TaskService: Task
    deactivate TaskRepository
    TaskService --> TaskController: Task
    deactivate TaskService
    TaskController -> Frontend: Task (HTTP 201 CREATED)
    deactivate TaskController
    Frontend -> User: Tarefa criada do tipo Prazo
    deactivate Frontend
end

@enduml
