@startuml diagrama.puml

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_WITH_LEGEND()


System_Boundary(Context, "Sistema To-Do List") {
    Container(SoftwareSystem, "Software System") {
        Component(API, "API") {
            [TaskController]
            [TaskService]
            [TaskRepository]
        }
        Container(Database, "Database") {
            [Task Table]
        }
    }
    
    Person(User, "User")
}

Rel(User, API, "Uses")
Rel(API, Database, "Stores data in")
Rel(API, TaskService, "Uses")
Rel(TaskController, TaskService, "Uses")
Rel(TaskService, TaskRepository, "Uses")

@enduml
