@startuml diagramaSequenciaUC03

title Diagrama de Sequência referente ao UC-03: Excluir Tarefa

actor User
participant Frontend
participant TaskController
participant TaskService
participant TaskRepository
participant Database

User -> Frontend: Excluir uma tarefa (id)
activate Frontend
Frontend -> TaskController: DELETE /task/{id}
activate TaskController
TaskController -> TaskService: deleteTask(id)
activate TaskService
TaskService -> TaskRepository: deleteById(id)
activate TaskRepository
TaskRepository -> Database: DELETE FROM tasks WHERE id = {id}
activate Database
Database --> TaskRepository: Deleção realizada com sucesso
deactivate Database
TaskRepository --> TaskService: void
deactivate TaskRepository
TaskService --> TaskController: void
deactivate TaskService
TaskController -> Frontend: HTTP 204 NO CONTENT
deactivate TaskController
Frontend -> User: Confirmação de tarefa excluída
deactivate Frontend

@enduml
